version: '3'
services:
  observant:
    user: bot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_IMAGE: ${DOCKER_IMAGE:-swift:latest}
    
    environment:
      - DISCORD_NICKNAME
      - DISCORD_PLAYING
      # - DISCORD_TOKEN # should be provided by .env
      - ENV_ARGS
      - ENV_COMMAND
      # - GITHUB_TOKEN # should be provided by .env
      - TARGET_ARGS_TO_USE_STDIN
      - TARGET_CLI
      - TARGET_DEFAULT_ARGS
      - TIMEOUT_ARGS
      - TIMEOUT_COMMAND

    env_file: .env
    tty: true
