version: '3'
services:
  observant:
    user: bot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_IMAGE: ${DOCKER_IMAGE:-ubuntu:18.04}
    
    environment:
      - DISCORD_NICKNAME
      - DISCORD_PLAYING
      - DISCORD_TOKEN
      - ENV_ARGS
      - ENV_COMMAND
      - TARGET_ARGS_TO_USE_STDIN
      - TARGET_CLI
      - TARGET_DEFAULT_ARGS
      - TIMEOUT_ARGS
      - TIMEOUT_COMMAND
    tty: true
