version: '3'
services:
  observant:
    build:
      context: devcontainers
      dockerfile: Dockerfile
      args:
        DOCKER_IMAGE: ${DOCKER_IMAGE:-ubuntu:18.04}
    volumes:
      - ./devcontainers/.vscode-server/extensions:/home/bot/.vscode-server/extensions
      - ./devcontainers/.vscode-server/extensions:/home/bot/.vscode-server-insiders/extensions
      - .:/workspace
      - ./devcontainers/observant/launch.json:/workspace/.vscode/launch.json
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file: devcontainers/observant/.env
  
  lazy:
    user: bot
    build:
      context: devcontainers
      dockerfile: Dockerfile
      args:
        DOCKER_IMAGE: ${DOCKER_IMAGE:-swift:latest}
    volumes:
      - ./devcontainers/.vscode-server/extensions:/home/bot/.vscode-server/extensions
      - ./devcontainers/.vscode-server/extensions:/home/bot/.vscode-server-insiders/extensions
      - .:/workspace
      - ./devcontainers/lazy/launch.json:/workspace/.vscode/launch.json
    command: /bin/sh -c "while sleep 1000; do :; done"    
    env_file: devcontainers/lazy/.env
