name: Test

on:
  push:
    branches: [master]
    paths: 
      - '.github/workflows/test.yml'
      - 'bot/**/*.ts'
      - '*.ts'
  pull_request:
    paths: 
      - '.github/workflows/test.yml'
      - 'bot/**/*.ts'
      - '*.ts'

jobs:
  Deno:
    runs-on: ubuntu-latest
    container:
      image: denoland/deno:1.14.0
    steps:
      - uses: actions/checkout@v1
      - run: deno test bot
